name: gbk2utf
description: A sample command-line application with basic argument parsing.
version: 1.0.0
repository: https://github.com/sr229/gbk2utf

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
