name: gbk2utf
description: A simple library/CLI for converting GBK-Encoded files to UTF-8
version: 1.0.0
repository: https://github.com/sr229/gbk2utf

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
